; PlatformIO Project Configuration for ESP32 Desktop Ornament
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
board_build.partitions = default_ffat.csv
board_build.ffat_size = 1M

; TFT_eSPI: load custom User_Setup.h from include/
build_flags =
    -DUSER_SETUP_LOADED=1
    -DCORE_DEBUG_LEVEL=1

lib_deps =
    bodmer/TFT_eSPI
    adafruit/DHT sensor library
    adafruit/Adafruit Unified Sensor
    bblanchon/ArduinoJson
    arduino-libraries/NTPClient

monitor_speed = 115200
